rees46/android-sdk

personalizatio-sdk/src/main/java/com/personalizatio/Params.java
sample/src/main/java/com/personalizatio/sample/AbstractMainActivity.java

https://github.com/rees46/planning/issues/736

feat: add full wish

---

personalizatio-sdk/src/main/java/com/personalizatio/stories/views/storyItem/StoryItemView.java

При выполнении задачи https://github.com/rees46/planning/issues/108 были допущены ошибки по отображению текстов для product элемента

fix: corrected showing product texts

---

.github/workflows/checks.yaml
.github/workflows/publish.yaml
publish.gradle

https://github.com/rees46/planning/issues/862#issuecomment-2189041913
Добавила переменные для публикации вариантов

feat: publish variants

---

README.md
personalizatio-sdk/src/main/kotlin/com/personalizatio/SDK.kt
personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/StoriesManager.kt
personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/views/StoriesView.kt

https://github.com/rees46/planning/issues/826
Заменен метод показа кампании по id на показ блока сторис по коду

Feat/ show stories by code

---

README.md

https://github.com/rees46/planning/issues/1225

Docs: updated readme

---

personalizatio-sdk/src/main/kotlin/com/personalizatio/RegisterManager.kt
personalizatio-sdk/src/main/kotlin/com/personalizatio/SDK.kt

https://github.com/rees46/planning/issues/1337

Fix: return set push token notification method to sdk

---

personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationHandler.kt

Добавила поле analytics_label
https://github.com/rees46/planning/issues/300#issuecomment-2247467765

Feat: add analytics label field to mobile push

---

personalizatio-sdk/src/main/kotlin/com/personalizatio/RegisterManager.kt

https://github.com/rees46/planning/issues/1394
- Исправлена обработка получения did, sid и token.
- Исправлено условие для автоматической отправки токена

Fix: incorrect handling of receiving did

---

.github/workflows/publish.yaml

Feat: github

---

personalization-sdk/build.gradle
publish.gradle

Изменила пути до проекта
https://github.com/rees46/planning/issues/1400#issuecomment-2271729244

chore: change android-sdk repository paths

---

personalization-sdk/build.gradle

https://github.com/rees46/planning/issues/1416

Fix: publish github packages

---

personalization-sdk/build.gradle

https://github.com/rees46/planning/issues/1416#issuecomment-2275010762

Revert: version bump

---

personalization-sdk/src/main/kotlin/com/personalization/features/search/SearchManagerImpl.kt

Быстрое исправление ошибки в работе поиска:
https://github.com/rees46/planning/issues/1484

Fix: search

---

personalizatio-sdk/src/main/java/com/personalizatio/stories/views/StoriesView.java

- https://github.com/rees46/planning/issues/1356

Fix: Nullpointer in StoriesView

---

personalization-sdk/build.gradle
sample/build.gradle

- https://github.com/rees46/planning/issues/1699

chore: Downgrade java version

---

personalization-sdk/src/main/kotlin/com/personalization/stories/views/StoriesView.kt
personalization-sdk/src/main/kotlin/com/personalization/stories/views/StoryDialog.kt
personalization-sdk/src/main/kotlin/com/personalization/stories/views/StoryView.kt
personalization-sdk/src/main/kotlin/com/personalization/stories/views/storyItem/StoryItemView.kt
personalization-sdk/src/main/res/values/styles.xml
sample/src/main/kotlin/com/personalization/sample/AbstractMainActivity.kt
sample/src/main/res/layout/activity_main.xml

- https://github.com/rees46/planning/issues/1740

feat: Added optional parameter for opening webview from browser

---

publish.gradle

- https://github.com/rees46/planning/issues/1752

chore: Remove publication developer info

---

personalization-sdk/src/main/kotlin/com/personalization/OnClickListener.kt
personalization-sdk/src/main/kotlin/com/personalization/OnLinkClickListener.kt
personalization-sdk/src/main/kotlin/com/personalization/stories/viewAdapters/ProductsAdapter.kt
personalization-sdk/src/main/kotlin/com/personalization/stories/views/StoriesView.kt
personalization-sdk/src/main/kotlin/com/personalization/stories/views/storyItem/StoryItemView.kt
sample/src/main/kotlin/com/personalization/sample/AbstractMainActivity.kt

- https://github.com/rees46/planning/issues/1905

feat: Added optional hiding bottom sheet and remove required listener

---

personalization-sdk/src/main/kotlin/com/personalization/api/managers/ProductsManager.kt
personalization-sdk/src/main/kotlin/com/personalization/features/products/impl/ProductsManagerImpl.kt

- https://github.com/rees46/development/issues/415

feat: Added func for getting product item info

---

personalization-sdk/src/main/kotlin/com/personalization/SDK.kt
personalization-sdk/src/personaclick/kotlin/com/personaclick/sdk/Personaclick.kt
personalization-sdk/src/rees46/kotlin/com/rees46/sdk/REES46.kt

- https://github.com/rees46/development/issues/2220

chore: Remove useless notificationType and notificationId

---

personalization-sdk/src/main/kotlin/com/personalization/api/managers/SearchManager.kt
personalization-sdk/src/main/kotlin/com/personalization/api/params/SearchParams.kt
personalization-sdk/src/main/kotlin/com/personalization/features/search/impl/SearchManagerImpl.kt

**Таска:**
- https://github.com/rees46/development/issues/2565
**Пруфы:**

feat(search): exclude brands from instant search

---

personalization-sdk/src/main/kotlin/com/personalization/SDK.kt
personalization-sdk/src/main/kotlin/com/personalization/stories/StoriesManager.kt
personalization-sdk/src/main/kotlin/com/personalization/stories/viewAdapters/ProductsAdapter.kt
personalization-sdk/src/main/kotlin/com/personalization/stories/views/StoriesView.kt
personalization-sdk/src/main/kotlin/com/personalization/stories/views/StoryDialog.kt
personalization-sdk/src/main/kotlin/com/personalization/stories/views/StoryView.kt
personalization-sdk/src/main/kotlin/com/personalization/stories/views/storyItem/StoryItemView.kt

**Таска:**
- https://github.com/rees46/development/issues/2598
**Пруф:**
https://github.com/user-attachments/assets/1e40ca40-411e-4eb2-b4c0-95b5ee0bd780

feat(stories): add support for onItemClickListener in stories

---

.github/workflows/sync.yaml

for https://github.com/rees46/development/issues/2654

feat(github): sync action

---

.github/workflows/publish.yaml

for https://github.com/rees46/development/issues/2723

refactor(github): useless

---

.github/workflows/publish.yaml

for https://github.com/rees46/development/issues/2723

chore(github): useless

---

.github/workflows/publish.yaml

забыл убрать - ссылался на ветку для разработки

fix(github): branch name

---

.github/workflows/publish.yaml
personalization-sdk/build.gradle

closes https://github.com/rees46/development/issues/2787
- проверил паблиш без зависимости, прошел
- proof: https://github.com/rees46/android-sdk/actions/runs/14447429687

fix(personalizaton): deps

---

.github/workflows/constants/replacements.yml
.github/workflows/publish.yaml
.releaserc.yml
build.gradle
gradle/publishing/maven.gradle

for https://github.com/rees46/development/issues/2654
- правки в gradlew.properties, неверно обрабатывал версию
- расширил конфиг releaserc, не проходил паблиш на gh-releases
- добавил в replacements hash коммита для паблиша
- делаю .sh executable

chore(github): debug enveronment

---

version.properties

chore(common): trigger

---

settings.gradle

for https://github.com/rees46/development/issues/2654#issuecomment-2840111953
- триггер воркфлоу. ошибся в файлах

feat(common): trigger workflow

---

.github/workflows/constants/replacements.yml
.github/workflows/version.yaml
settings.gradle

for https://github.com/rees46/development/issues/2654
merge after https://github.com/rees46/workflow/pull/296
- добавляю replacements
- прокидываю токен

fix(github): rm need from replacement ignore

---

personalization-sdk/src/main/kotlin/com/personalization/SDK.kt

**Таска:**
- https://t.me/c/2243138785/1153/45984
**Пруфы:**
<details>
</details>

Optional api domain

---

.github/workflows/version.yaml

for https://github.com/rees46/development/issues/2939
- создал versioner-app - https://github.com/organizations/rees46/settings/apps/r46-versioner
- добавил ему минимально необходимые для версионирования права
- поменял нейминги в репозиториях, где версионирование разделено от паблиша
--
proof:
- тестировал изолированно работу с фс и создание пулл-реквеста. комплексно работат только при мердже в мастер. тестировал только в android-sdk, все репозитории работают по одному воркфлоу, расхождений быть не должно
- работа с фс - https://github.com/rees46/android-sdk/actions/runs/15023293960/job/42219882185
- сделали чекаут, прочитали файлы на локалке. скрипт не запустился, потмоучто работает только с push на мастер
- создание ПР - https://github.com/rees46/android-sdk/actions/runs/15034182042/job …

refactor(github): app secrets to versioner app

---

.github/workflows/publish.yaml

for https://github.com/rees46/development/issues/2939
proof https://github.com/rees46/development/issues/2939#issuecomment-2887708657
- меняю сикреты на новое приложение с минимально необходимыми разрешениями

refactor(github): secret namings

---

.github/workflows/auto-merge-sync-pr.yml.bak

for https://github.com/rees46/development/issues/2976
- добавляю auto-merge-sync-branch-workflow, в закомментированом виде
- при синхронизации - раскомментируется
- в infrastructure добавил replacements - https://github.com/rees46/infrastructure/pull/2729

feat(githoub): auto merge sync branch workflow
